version: '3.8'
services:
  device-backend:
    image: energy-crud-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy-crud-app
    restart: unless-stopped
    ports:
      - "8080:8080"