### Utwórz konfigurację
POST http://localhost:8080/configurations
Content-Type: application/json

{
  "deviceId": "device1",
  "configuration": "Your_configuration_data_here"
}

###

### Odczytaj konfigurację
GET http://localhost:8080/configurations/1

###

### Aktualizuj konfigurację
PUT http://localhost:8080/configurations/2
Content-Type: application/json

{
  "deviceId": "device123",
  "configuration": "New_configuration_data_here"
}

###

### Usuń konfigurację
DELETE http://localhost:8080/configurations/2

